spring:
  application:
    name:
      flower-springboot
  datasource:
    username:
      root
    password:
      chentao1we
    url:
      jdbc:mysql://localhost:3306/flower
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB #???????
  data:
    redis:
      host: localhost
      port: 6379
mybatis-plus:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #????????
  global-config:
    db-config:
      id-type: auto
